IO:

  RUNNING: True
  ZOOM_SPEED: 0.05

VISUAL:

  SETTINGS:

    WIDTH: 1280
    HEIGHT: 720
    ZOOM: 1
    FONTSIZE: 24
    FONTSIZE_TITLE: 48
    BOARD_SQUARE_SIZE: 100
    WORLD_ORIGIN: [400, 100]
    BOARD_ORIGIN: [0, 0]
    PERSPECTIVE: BLACK
    BOARD_BLACK_COLOR: BOARD_DARK
    BOARD_WHITE_COLOR: BOARD_LIGHT
    BACKGROUND_COLOR: BLACK
    BOARD_SELECTED_COLOR: LIGHT_GREEN
    BOARD_LAST_MOVE_TO_COLOR: LIGHT_YELLOW
    BOARD_LAST_MOVE_FROM_COLOR: DARK_YELLOW
    BOARD_VALID_MOVES_COLOR: LIGHT_LIGHT_GREEN
    FONT_COLOR: WHITE

  COLORS:
  
    WHITE: [255, 255, 255]
    GRAY: [50, 50, 50]
    BLACK: [0, 0, 0]
    RED: [255, 0, 0]
    ORANGE: [255, 125, 0]
    YELLOW: [255, 225, 0]
    GREEN: [0, 255, 0]
    CYAN: [0, 255, 255]
    BLUE: [0, 0, 255]
    PURPLE: [255, 0, 255]
    MAGENTA: [255, 0, 125]

    BOARD_DARK: [238, 238, 210]
    BOARD_LIGHT: [118, 150, 86]
    LIGHT_GREEN: [100, 255, 100]
    LIGHT_LIGHT_GREEN: [200, 255, 200]
    DARK_YELLOW: [200, 200, 90]
    LIGHT_YELLOW: [255, 255, 100]

CHESS:
  BOARD_RANKS: 8
  BOARD_FILES: 8
  MAX_HALF_MOVES: 50
  PIECE_NUMBERS: {"NONE": 0, "PAWN": 1, "KNIGHT": 2, "BISHOP": 3, "ROOK": 4, "QUEEN": 5, "KING": 6, "WHITE": 1, "BLACK": 2}
  PIECE_SCORES: {"PAWN": 1, "KNIGHT": 3, "BISHOP": 3, "ROOK": 4, "QUEEN": 9, "KING": 100, "CHECK": 0, "CHECKMATE": 1000}
  BOARD: rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 0

AI:
  PAUSED: False
  WHITE_PLAYER: CUSTOM
  BLACK_PLAYER: PLAYER
  CUSTOM_DEPTH: 1